### ISSUE TITLE
Start/stop behaviour

### ISSUE THREAD

**Issue by vortex314** [michaelbecker/freertos-addons#26]
Hi Michael, 
as I was looking for a freeRTOS simulation on top of Linux I found your repo, which looked very interesting. 
Also the C++ wrappers are a nice gift.

I can compile and run the code within CodeLite. 
But the code seems to freeze until I click "Start or Continue Debugger". 

I notice 6 threads ( 2 of which are created by using paho.mqtt.c Linux version ), I see that the main task is hanging in : 
0  0x00007ffff707e2d1  __pthread_kill  /build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/pthread_kill.c  57
1  0x000055555558259d  SuspendThread  /home/lieven/workspace/freertos-addons/Linux/portable/GCC/Linux/port.c  166
2  0x000055555558372d  vPortYield  /home/lieven/workspace/freertos-addons/Linux/portable/GCC/Linux/port.c  755
3  0x00005555555799f1  xQueueReceive  /home/lieven/workspace/FreeRTOSv10.1.1/FreeRTOS/Source/queue.c  1378
4  0x000055555555ccc2  Mailbox::dequeue  /home/lieven/workspace/microAkka/src/Akka.cpp  290
5  0x000055555555eb17  MessageDispatcher::execute  /home/lieven/workspace/microAkka/src/Akka.cpp  692
6  0x000055555557f4ab  main_task  /home/lieven/workspace/microAkka/src/main.cpp  39
7  0x0000555555582d55  ThreadStartWrapper  /home/lieven/workspace/freertos-addons/Linux/portable/GCC/Linux/port.c  440
8  0x00007ffff70766db  start_thread  /build/glibc-OTsEL5/glibc-2.27/nptl/pthread_create.c  463
9  0x00007ffff6d9f88f  clone  /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S  95

Any idea what could be wrong ? 
Maybe the combination of a linux specific MQTT ?

Code is partly here : https://github.com/vortex314/microAkka

regards
Lieven

**Comment by vortex314** [comment]
Debugging with GDB comes to a similar result , see some gdb debugging below where the process stalls
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Debug/microAkka...done.
(gdb) run
Starting program: /home/lieven/workspace/microAkka/Debug/microAkka 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Running as PID: 23566
[New Thread 0x7ffff6c7d700 (LWP 23571)]

Thread 2 "microAkka" received signal SIGUSR1, User defined signal 1.
[Switching to Thread 0x7ffff6c7d700 (LWP 23571)]
__pthread_kill (threadid=<optimized out>, signo=10) at ../sysdeps/unix/sysv/linux/pthread_kill.c:57
57	../sysdeps/unix/sysv/linux/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill (threadid=<optimized out>, signo=10) at ../sysdeps/unix/sysv/linux/pthread_kill.c:57
#1  0x00005555555789b1 in SuspendThread (Thread=140737333679872) at /home/lieven/workspace/microAkka/Linux/port.c:166
#2  0x000055555557916c in ThreadStartWrapper (pvParams=0x5555557d2cc0 <pxThreads>) at /home/lieven/workspace/microAkka/Linux/port.c:434
#3  0x00007ffff70766db in start_thread (arg=0x7ffff6c7d700) at pthread_create.c:463
#4  0x00007ffff6d9f88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) threads
Undefined command: "threads".  Try "help".
(gdb) thread
[Current thread is 2 (Thread 0x7ffff6c7d700 (LWP 23571))]
(gdb) info thread
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fcf740 (LWP 23566) "microAkka" 0x0000555555579505 in pxPortInitialiseStack (pxTopOfStack=0x555555891f78, 
    pxCode=0x555555575713 <main_task(void*)>, pvParameters=0x5555557d2be0 <defaultDispatcher>) at /home/lieven/workspace/microAkka/Linux/port.c:514
* 2    Thread 0x7ffff6c7d700 (LWP 23571) "microAkka" __pthread_kill (threadid=<optimized out>, signo=10) at ../sysdeps/unix/sysv/linux/pthread_kill.c:57
(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff7fcf740 (LWP 23566))]
#0  0x0000555555579505 in pxPortInitialiseStack (pxTopOfStack=0x555555891f78, pxCode=0x555555575713 <main_task(void*)>, 
    pvParameters=0x5555557d2be0 <defaultDispatcher>) at /home/lieven/workspace/microAkka/Linux/port.c:514
514	    while ( xSentinel == 0 );
(gdb) bt
#0  0x0000555555579505 in pxPortInitialiseStack (pxTopOfStack=0x555555891f78, pxCode=0x555555575713 <main_task(void*)>, 
    pvParameters=0x5555557d2be0 <defaultDispatcher>) at /home/lieven/workspace/microAkka/Linux/port.c:514
#1  0x0000555555570de7 in prvInitialiseNewTask (pxTaskCode=0x555555575713 <main_task(void*)>, pcName=0x5555555b030d "mqtt_task", ulStackDepth=10000, 
    pvParameters=0x5555557d2be0 <defaultDispatcher>, uxPriority=2, pxCreatedTask=0x0, pxNewTCB=0x555555891f90, xRegions=0x0)
    at /home/lieven/workspace/microAkka/FreeRTOS/tasks.c:1027
#2  0x0000555555570c02 in xTaskCreate (pxTaskCode=0x555555575713 <main_task(void*)>, pcName=0x5555555b030d "mqtt_task", usStackDepth=10000, 
    pvParameters=0x5555557d2be0 <defaultDispatcher>, uxPriority=2, pxCreatedTask=0x0) at /home/lieven/workspace/microAkka/FreeRTOS/tasks.c:823
#3  0x0000555555575a84 in main () at /home/lieven/workspace/microAkka/src/main.cpp:77
(gdb)

**Comment by vortex314** [comment]
Ok, found my answer here : https://www.freertos.org/FreeRTOS-simulator-for-Linux.html
GDB settings to apply
